services:
  - type: web
    name: sistema-fardamentos
    env: python
    plan: free
    runtime: python
    pythonVersion: "3.9.18"
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
